version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
  pre_build:
    commands:
      - npm run cy:verify
      - npm run cy:info
  build:
    commands:
      - npm run start &
      - npx cypress run

# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 12
#     commands:
#       - echo Installing source NPM dependencies...
#       - yarn install
#       - yarn add wait-on pm2
#       - apt-get update -y && apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
#       - yarn add mocha mochawesome mochawesome-merge mochawesome-report-generator
#       - npx pm2 start npm -- start
#       - 'npx wait-on http://localhost:3000'
#   pre_build:
#     commands:
#       - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
#   build:
#     commands:
#       - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
#       - npx pm2 kill
#       - echo Build started on `date`
#       - yarn build

# artifacts:
#   base-directory: ./build
#   files:
#     - '**/*'

# cache:
#   paths:
#     - './node_modules/**/*'
